import React, { useEffect, useState, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Project, Task, TaskStatus, AITaskItem } from '../types';
import { projectService } from '../services/projects';
import { taskService, CreateTaskPayload, UpdateTaskPayload } from '../services/tasks';
import { useToast } from '../context/ToastContext';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { TaskCard } from '../components/tasks/TaskCard';
import { TaskFormModal } from '../components/tasks/TaskFormModal';
import { TaskDetailModal } from '../components/tasks/TaskDetailModal';
import { ProjectFormModal } from '../components/projects/ProjectFormModal';
import { GenerateTasksModal } from '../components/ai/GenerateTasksModal';
import { EmptyState } from '../components/ui/EmptyState';
import { Skeleton } from '../components/ui/Skeleton';
import {
  ArrowLeft,
  Calendar,
  CheckCircle2,
  Edit2,
  Plus,
  Sparkles,
  Trash2,
  CheckSquare,
} from 'lucide-react';

export const ProjectDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { addToast } = useToast();

  const [project, setProject] = useState<Project | null>(null);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Modals state
  const [isTaskFormOpen, setIsTaskFormOpen] = useState(false);
  const [taskToEdit, setTaskToEdit] = useState<Task | null>(null);
  const [selectedTaskForDetail, setSelectedTaskForDetail] = useState<Task | null>(null);
  const [isProjectFormOpen, setIsProjectFormOpen] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);

  const loadData = useCallback(async () => {
    if (!id) return;
    setIsLoading(true);
    try {
      const [p, t] = await Promise.all([
        projectService.getProject(id),
        taskService.listTasks({ projectId: id }),
      ]);
      setProject(p);
      setTasks(t);
    } catch (err: any) {
      addToast('error', 'Error', err.message || 'Failed to load project details.');
      navigate('/projects');
    } finally {
      setIsLoading(false);
    }
  }, [id, addToast, navigate]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleStatusChange = async (taskId: string, newStatus: TaskStatus) => {
    try {
      await taskService.updateTaskStatus(taskId, newStatus);
      loadData();
    } catch (err: any) {
      addToast('error', 'Update Failed', err.message);
    }
  };

  const handleDeleteTask = async (taskId: string) => {
    try {
      await taskService.deleteTask(taskId);
      addToast('success', 'Task Deleted', 'Task removed successfully.');
      loadData();
    } catch (err: any) {
      addToast('error', 'Delete Failed', err.message);
    }
  };

  const handleCreateOrUpdateTask = async (data: CreateTaskPayload | UpdateTaskPayload) => {
    if (taskToEdit) {
      await taskService.updateTask(taskToEdit.id, data);
      addToast('success', 'Task Updated', 'Task updated successfully.');
    } else {
      await taskService.createTask(data as CreateTaskPayload);
      addToast('success', 'Task Created', 'New task added to project.');
    }
    loadData();
  };

  const handleSaveAITasks = async (aiTasks: Array<AITaskItem & { project_id: string }>) => {
    try {
      await taskService.createTasksBatch(
        aiTasks.map((t) => ({
          title: t.title,
          description: t.description,
          project_id: t.project_id,
          priority: t.priority,
          status: 'todo',
          tags: t.tags,
          estimated_hours: t.estimated_hours,
        }))
      );
      addToast('success', 'AI Tasks Added', `Created ${aiTasks.length} tasks generated by AI.`);
      loadData();
    } catch (err: any) {
      addToast('error', 'Failed to add AI tasks', err.message);
    }
  };

  const handleDeleteProject = async () => {
    if (!project) return;
    if (window.confirm(`Delete project "${project.name}" and all its tasks?`)) {
      try {
        await projectService.deleteProject(project.id);
        addToast('success', 'Project Deleted', 'Project has been deleted.');
        navigate('/projects');
      } catch (err: any) {
        addToast('error', 'Delete Failed', err.message);
      }
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-6 w-32" />
        <Skeleton className="h-44 w-full" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3].map((i) => (
            <Skeleton key={i} className="h-32" />
          ))}
        </div>
      </div>
    );
  }

  if (!project) return null;

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Back link */}
      <div>
        <Link
          to="/projects"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-gray-500 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Projects</span>
        </Link>
      </div>

      {/* Project Banner Card */}
      <div className="rounded-2xl bg-white dark:bg-gray-900 border border-gray-100 dark:border-gray-800 p-6 sm:p-8 shadow-sm space-y-6">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 pb-6 border-b border-gray-100 dark:border-gray-800">
          <div>
            <div className="flex items-center gap-2 flex-wrap mb-2">
              <Badge status={project.status}>{project.status.replace('_', ' ')}</Badge>
              <Badge priority={project.priority}>{project.priority}</Badge>
              <span className="text-xs font-medium text-gray-500 dark:text-gray-400 bg-gray-50 dark:bg-gray-800 px-2.5 py-0.5 rounded-full border border-gray-100 dark:border-gray-800">
                {project.category}
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 dark:text-white tracking-tight">
              {project.name}
            </h1>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2.5 flex-wrap">
            <Button
              variant="ai"
              size="sm"
              onClick={() => setIsAIModalOpen(true)}
              leftIcon={<Sparkles className="w-4 h-4" />}
            >
              Generate Tasks with AI
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={() => {
                setTaskToEdit(null);
                setIsTaskFormOpen(true);
              }}
              leftIcon={<Plus className="w-4 h-4" />}
            >
              Add Task
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsProjectFormOpen(true)}
              leftIcon={<Edit2 className="w-3.5 h-3.5" />}
            >
              Edit
            </Button>
            <Button
              variant="danger"
              size="sm"
              onClick={handleDeleteProject}
              leftIcon={<Trash2 className="w-3.5 h-3.5" />}
            >
              Delete
            </Button>
          </div>
        </div>

        {/* Project Description */}
        <p className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed max-w-3xl">
          {project.description || 'No detailed overview supplied for this project.'}
        </p>

        {/* Progress bar and timeline */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 pt-4 border-t border-gray-50 dark:border-gray-800">
          <div>
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Completion Rate
            </span>
            <div className="mt-1 flex items-center gap-2">
              <span className="text-2xl font-extrabold text-gray-900 dark:text-white">
                {project.progressPercentage}%
              </span>
              <span className="text-xs text-gray-400">
                ({project.completedTasks} of {project.totalTasks} tasks)
              </span>
            </div>
            <div className="mt-2 h-1.5 w-full bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
              <div
                className="bg-indigo-600 h-full rounded-full transition-all duration-300"
                style={{ width: `${project.progressPercentage}%` }}
              />
            </div>
          </div>

          <div>
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Target Deadline
            </span>
            <div className="mt-1 flex items-center gap-2 text-sm font-semibold text-gray-800 dark:text-gray-200">
              <Calendar className="w-4 h-4 text-indigo-500" />
              <span>
                {project.dueDate
                  ? new Date(project.dueDate).toLocaleDateString('en-US', {
                      month: 'long',
                      day: 'numeric',
                      year: 'numeric',
                    })
                  : 'Flexible timeline'}
              </span>
            </div>
          </div>

          <div>
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Workload
            </span>
            <div className="mt-1 flex items-center gap-2 text-sm font-semibold text-gray-800 dark:text-gray-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              <span>
                {tasks.filter((t) => t.status !== 'done').length} remaining action items
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Project Tasks Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <CheckSquare className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            <span>Tasks ({tasks.length})</span>
          </h2>

          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              setTaskToEdit(null);
              setIsTaskFormOpen(true);
            }}
            leftIcon={<Plus className="w-4 h-4" />}
          >
            New Task
          </Button>
        </div>

        {tasks.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {tasks.map((task) => (
              <TaskCard
                key={task.id}
                task={task}
                onStatusChange={handleStatusChange}
                onEdit={(t) => {
                  setTaskToEdit(t);
                  setIsTaskFormOpen(true);
                }}
                onDelete={handleDeleteTask}
                onViewDetails={(t) => setSelectedTaskForDetail(t)}
                onSummarize={(t) => setSelectedTaskForDetail(t)}
              />
            ))}
          </div>
        ) : (
          <EmptyState
            icon={<CheckSquare className="w-6 h-6" />}
            title="No tasks in this project"
            description="Create tasks manually or use our AI Copilot to generate an automated agile task breakdown."
            actionLabel="Generate with AI"
            onAction={() => setIsAIModalOpen(true)}
            actionIcon={<Sparkles className="w-4 h-4" />}
          />
        )}
      </div>

      {/* Modals */}
      <TaskFormModal
        isOpen={isTaskFormOpen}
        onClose={() => setIsTaskFormOpen(false)}
        onSubmit={handleCreateOrUpdateTask}
        taskToEdit={taskToEdit}
        projects={[project]}
        defaultProjectId={project.id}
      />

      <TaskDetailModal
        isOpen={!!selectedTaskForDetail}
        onClose={() => setSelectedTaskForDetail(null)}
        task={selectedTaskForDetail}
      />

      <ProjectFormModal
        isOpen={isProjectFormOpen}
        onClose={() => setIsProjectFormOpen(false)}
        onSubmit={async (data) => {
          await projectService.updateProject(project.id, data);
          addToast('success', 'Project Updated', 'Changes saved.');
          loadData();
        }}
        projectToEdit={project}
      />

      <GenerateTasksModal
        isOpen={isAIModalOpen}
        onClose={() => setIsAIModalOpen(false)}
        project={project}
        onSaveTasks={handleSaveAITasks}
      />
    </div>
  );
};
